version: '3.3'
services:

  yeti-api:
    build:
      context: ./yeti/
      dockerfile: ./extras/docker/prod/Dockerfile
    image: yeti
    entrypoint:
      - /docker-entrypoint.sh
    command: ['envshell']
    ports:
      - 8000:8000
    depends_on:
      - redis
      - arangodb
    environment:
      - TLDEXTRACT_CACHE=/tmp/tldextract.cache
    volumes:
      - /tmp/docker-yeti-exports:/opt/yeti/exports
      - D:\workspace\yeti\:/app/
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  frontend:
    build:
      context: ./yeti-feeds-frontend/
      dockerfile: ./docker/dev/Dockerfile
    image: yeti-feeds-frontend
    environment:
      - VUE_API_BACKEND=fastapi
    ports:
      - 8080:8080
    volumes:
      - ./yeti-feeds-frontend/:/app
    entrypoint:
      - /docker-entrypoint.sh
    command:
      - /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  redis:
    image: redis:latest

  arangodb:
    image: arangodb
    ports:
      - 127.0.0.1:8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=
