version: '3.3'
services:

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    image: yetiplatform/yeti-frontend:latest
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    image: yetiplatform/yeti:latest
    build:
      dockerfile: ./yeti/Dockerfile
    environment:
      - YETI_REDIS_HOST=prod-redis-1
      - YETI_REDIS_PORT=6379
      - YETI_REDIS_DATABASE=0
      - YETI_ARANGODB_HOST=prod-arangodb-1
      - YETI_ARANGODB_PORT=8529
      - YETI_ARANGODB_DATABASE=yeti
      - YETI_ARANGODB_USERNAME=root
      - YETI_ARANGODB_PASSWORD=
      - YETI_AUTH_SECRET_KEY=SECRET
      - YETI_AUTH_ALGORITHM=HS256
      - YETI_AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - YETI_AUTH_ENABLED=False
    entrypoint:
      - /docker-entrypoint.sh
    command: ["poetry", "run", "uvicorn", "core.web.webapp:app", "--host", "0.0.0.0"]
    ports:
      - 8000:8000
    depends_on:
      - redis
      - arangodb
    volumes:
      - /tmp/docker-yeti-exports:/opt/yeti/exports

  tasks:
    image: yetiplatform/yeti:latest
    build:
      dockerfile: ./yeti/Dockerfile
    environment:
      - YETI_REDIS_HOST=prod-redis-1
      - YETI_REDIS_PORT=6379
      - YETI_REDIS_DATABASE=0
      - YETI_ARANGODB_HOST=prod-arangodb-1
      - YETI_ARANGODB_PORT=8529
      - YETI_ARANGODB_DATABASE=yeti
      - YETI_ARANGODB_USERNAME=root
      - YETI_ARANGODB_PASSWORD=
      - YETI_AUTH_SECRET_KEY=SECRET
      - YETI_AUTH_ALGORITHM=HS256
      - YETI_AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - YETI_AUTH_ENABLED=False
    command: ['tasks']
    depends_on:
      - redis
      - arangodb
      - api

  redis:
    image: redis:latest

  arangodb:
    image: arangodb
    ports:
      - 127.0.0.1:8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=
